### ISSUE TITLE
how to print generator object to string?

### ISSUE THREAD

**Issue by Dagimal** [zembrodt/pymdb#14]
hello, I really like your project, but I have a little confusion, how do I print the actor to the string?
![object](https://user-images.githubusercontent.com/25417316/120097068-be5d4b00-c158-11eb-9012-7a9e1b864590.png)

**Comment by zembrodt** [comment]
Hi @Dagimal,

For methods that return a generator, you either need to iterate over each item that the generator yields until it's empty, or you can convert the generator into a list.

Given this example generator function:
```python
def test_generator(num):
    i = 0
    while i < num:
        i += 1
        yield i
```

Iterating over each item and printing can be done with a for loop:
```python
results = test_generator(3)
for num in results:
    print(num)
```
Output:
```
1
2
3
```

Converting the generator to a list can be done using the `list` constructor:
```python
results = test_generator(20)
results_list = list(results)
print(results_list)
```
Output:
```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```

Here is an article on the topic that may help:
https://realpython.com/introduction-to-python-generators/

**Comment by Dagimal** [comment]
Thank you very much for answering my question, your answer is very helpful 😇
